### ISSUE TITLE
Authentification

### ISSUE THREAD

**Issue by fa18swiss** [fa18swiss/MyWebCams#4]

**Comment by neginja** [comment]
Authentification avec la gem devise ok

**Comment by neginja** [comment]
Bootstraping des vuew générées en cours.

**Comment by neginja** [comment]
Ajout username en plus de l'email et login soit l'un soit l'autre ok

**Comment by neginja** [comment]
Bootstraping vue edition profile ok

**Comment by neginja** [comment]
Suppression compte ok -> vérifier la suppression en cascade (voir nouvelle issue)
