### ISSUE TITLE
Ajout  / modification / fiche webcam

### ISSUE THREAD

**Issue by fa18swiss** [fa18swiss/MyWebCams#6]

**Comment by fa18swiss** [comment]
regexp for image url
/https?:[/]{2}[\a-z][\w/.]+((jpe?g)|(png)|gif)/i
/https?:[/]{2}([a-z][a-z0-9]+.)+[a-z][a-z0-9]+[/a-z0-9-_]+.((jpe?g)|(png)|gif)/i
2nd is better

**Comment by neginja** [comment]
Terminé
